#-------------------------------------------------------------------------------
#Application constants
#-------------------------------------------------------------------------------
#comm.isDevMode=false
comm.isDevMode=true
spring.application.name=inventory-api
#ems.url = https://ems.baust.edu.bd

server.port=8086
#pdf.service.url=http://localhost:8100

#server.port=8085
#server.servlet.context-path=/inventory-api

#-------------------------------------------------------------------------------
#Database
#-------------------------------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5433/inventory_1
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=300
spring.jpa.properties.hibernate.order_inserts=false
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=ERROR
spring.main.allow-circular-references=true
#logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.format_sql=true